name: Update RAG Index

on:
  push:
    paths:
      - "me/**"
      - "rag/embedder.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install openai numpy pypdf

      - name: Generate embeddings
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python rag/embedder.py

      - name: Commit and push embeddings
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add rag/vector_store.json
          git commit -m "Auto-update RAG embeddings"
          git push
